### ISSUE TITLE
Next track is not playing, I need to press random Space / Enter / Up / Down to continue :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [DECE2183/yamusic-tui#17]
![Image](https://github.com/user-attachments/assets/9ae73bfc-f3a6-4f9a-87b9-a5188c0e326c)

**Comment by MZhuvka** [comment]
are you specifically pressing left arrow(not down arrow) to skip the track, or is it an automatic thing?

**Comment by vitaly-zdanevich** [comment]
Just after one track - I am not always hear the next :(

Tried only in `my wave`.

**Comment by MZhuvka** [comment]
did you change your buffersize? might be the reason

**Comment by MZhuvka** [comment]
Cannot even get it to play **a** track on arm64. 
Will retry when I am at home.

**Comment by MZhuvka** [comment]
How often does this happen to you? I've never had this happen on either Windows or Fedora (tried about 20 times).

**Comment by DECE2183** [comment]
Can you try to build it with `nomedia` tag and test that version?

**Comment by vitaly-zdanevich** [comment]
Please say the command, I do not understand how...

**Comment by DECE2183** [comment]
```
go build -tags=nomedia
```

**Comment by vitaly-zdanevich** [comment]
Tried - no, still stops after a few tracks, in `my wave` :(

**Comment by DECE2183** [comment]
Could you build the last commit and check if any errors appear? To show errors its need to put `show-errors: true` line to the config file. The output log file will be located at system temp directory in the `yamusic-tui` subdirectory.

**Comment by vitaly-zdanevich** [comment]
Tried - again stop after first track :(

Log:

    [ ERROR ][(2) 13:52:04] - failed to download track [30233289]: error code 410

**Comment by MZhuvka** [comment]
this is probably relevant:
https://yandex-music.readthedocs.io/en/main/yandex_music.download_info.html#yandex_music.download_info.DownloadInfo.get_direct_link

> Метод доступен только одну минуту с момента получения информации о загрузке, иначе **410** ошибка!

this is for python, though. but i think that this is the reason

**Comment by DECE2183** [comment]
This shouldn't happen because the track downloads almost instantly after obtaining the information

**Comment by MZhuvka** [comment]
this is a really dumb fix, but could you try building this and see if the issue persists? https://github.com/MZhuvka/yamusic-tui/tree/issue17-fix

**Comment by MZhuvka** [comment]
maybe your system/isp provides some weird request caching that messes with the app? crazy idea, but everything is possible...

**Comment by vitaly-zdanevich** [comment]
Still 410, silence after the first track.

**Comment by DECE2183** [comment]
@vitaly-zdanevich can you test the last commit? This is a slightly modified fix made by @MZhuvka.

**Comment by vitaly-zdanevich** [comment]
Updated, again stopped after the first track. No logs:

```
$ cat /tmp/yamusic-tui/
101275911.jpg  1114290.jpg    19716257.jpg   71399160.jpg   733606.jpg     metadata.mp3   
```

Config:

```
token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
buffer-size-ms: 80
rewind-duration-s: 5
volume: 0.5
volume-step: 0.05
cache-tracks: likes
search:
    artists: true
    albums: false
    playlists: false
controls:
    quit: ctrl+q,ctrl+c
    apply: enter
    cancel: esc
    cursor-up: up
    cursor-down: down
    show-all-kyes: '?'
    show-errors: true,
    playlists-up: ctrl+up
    playlists-down: ctrl+down
    playlists-rename: ctrl+r
    tracks-like: l
    tracks-add-to-playlist: a
    tracks-remove-from-playlist: ctrl+a
    tracks-share: ctrl+s
    tracks-shuffle: ctrl+x
    tracks-search: ctrl+f
    player-pause: ' '
    player-next: right
    player-previous: left
    player-rewind-forward: ctrl+right
    player-rewind-backward: ctrl+left
    player-like: L
    player-cache: S
    player-vol-up: +,=
    player-vol-donw: '-'
```
